# Generated by Django 3.2.7 on 2021-10-04 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('django_flex_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False, verbose_name='verified')),
                ('timeout', models.DateTimeField(blank=True, null=True, verbose_name='verification timeout')),
                ('failure_count', models.PositiveIntegerField(default=0, verbose_name='verification failure count')),
                ('password', models.CharField(blank=True, max_length=256, null=True, verbose_name='password')),
                ('expiration', models.DateTimeField(blank=True, null=True, verbose_name='expiration')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False, verbose_name='verified')),
                ('timeout', models.DateTimeField(blank=True, null=True, verbose_name='verification timeout')),
                ('failure_count', models.PositiveIntegerField(default=0, verbose_name='verification failure count')),
                ('password', models.CharField(blank=True, max_length=256, null=True, verbose_name='password')),
                ('expiration', models.DateTimeField(blank=True, null=True, verbose_name='expiration')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
